server {
    listen 80;
    server_name just-blog.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name just-blog.local;

    ssl_certificate /etc/nginx/certs/just-blog.local.crt;
    ssl_certificate_key /etc/nginx/certs/just-blog.local.key;

    root /var/www/html/just-blog/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
